language: cpp
dist: xenial

addons:
  apt:
    packages:
    - qtbase5-dev
    - qttools5-dev-tools
    - libqt5opengl5-dev
    - libusb-1.0-0-dev
    - libfftw3-dev
    - binutils-dev
    - rpm

matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install cmake --user; fi
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
  - chmod +x ./appimagetool-*.AppImage
  - ./appimagetool-*.AppImage deploy appdir/usr/share/applications/*.desktop
  - ./appimagetool-*.AppImage appdir/

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh OpenHantek*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
